development:
  adapter: postgresql
  encoding: unicode
  database: social_biblio_development
  host: localhost
  pool: 5
  timeout: 5000
  user: action

test:
  adapter: postgresql
  encoding: unicode
  database: social_biblio_test
  host: localhost
  pool: 5
  timeout: 5000
  user: action

production:
  adapter: postgresql
  encoding: unicode
  database: social_biblio_production
  host: localhost
  pool: 5
  timeout: 5000
  user: action
